name: GDC Trend Mailing
on:
  schedule:
    - cron: '0 23 * * 0-4' 
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with: { python-version: '3.10' }
    - run: pip install -r requirements.txt
    - env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python main.py
